# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Goat1ee's profile"
title_separator          : "-"
name                     : &name "Goat1ee"
description              : &description "Professionals focusing on AI, big models, artificial intelligence and data analysis"
url                      : https://goat1ee.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "cafc51d9824ce0da43c552a7e670c241.jpg"
  name             : "李伟龙"
  pronouns         : "he/his"  
  bio              : "Master student at Dalian University of Foreign Languages, focusing on AI and data analysis"
  location         : "Dalian"
  employer         : ""
  uri              : # URL
  email            : "18704701007@163.com" 

  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?user=MzD4WLMAAAAJ&hl=zh-CN"
  impactstory      : # URL
  orcid            : "https://orcid.org/0009-0006-3707-9316"
  semantic         : # URL
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "goat1ee.github.io"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  bluesky          : #"bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : '一把火烧了草原'
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username


